import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { signIn, signOut, useSession } from "next-auth/react";
import Link from "next/link";
import Layout from "../components/stylecomponents/logic/layout";
import Header from "../components/stylecomponents/logic/header";
const Home: NextPage = () => {
  const { data, status } = useSession();

  data ? console.log(data) : console.log("pailis");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
        <Layout>
          <Header />
          {status === "loading" && <p>Loading...</p>}
          {status === "unauthenticated" && (
            <button onClick={() => signIn()}>Sign In</button>
          )}
          {status === "authenticated" && (
            <button onClick={() => signOut()}>Sign Out</button>
          )}
          {data && (
            <Link
              href={`dashboard/${JSON.parse(JSON.stringify(data.user.email))}`}
            >
              <a>Go to dashboard</a>
            </Link>
          )}
        </Layout>
    </div>
  );
};

export default Home;
